controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - joint6
      - joint7
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: arm_zero
  - group: gripper
    pose: gripper_full_close