arm_group_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint1, joint2, joint3, joint4, virtual_roll_joint, virtual_yaw_joint]

gripper_group_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint5, joint6]

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
