controller_list:
  - name: fake_hand_ee_controller
    type: $(arg fake_execution_type)
    joints:
      - joint5
      - joint6
  - name: fake_arm_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
initial:  # Define initial robot poses per group
  - group: hand_ee
    pose: hand_zero
  - group: arm_robot
    pose: arm_home