moveit_sim_hw_interface:
  joint_model_group: arm_group
  joint_model_group_pose: arm_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - gripper
    - virtual_roll_joint
    - virtual_yaw_joint
  sim_control_mode: 1  # 0: position, 1: velocity


joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - virtual_roll_joint
      - virtual_yaw_joint
    gains:
      joint1:
        p: 100.0
        i: 0.0
        d: 10.0
        i_clamp: 1.0  # Optional: limit for integral term
      joint2:
        p: 100.0
        i: 0.0
        d: 10.0
        i_clamp: 1.0
      joint3:
        p: 100.0
        i: 0.0
        d: 10.0
        i_clamp: 1.0
      joint4:
        p: 100.0
        i: 0.0
        d: 10.0
        i_clamp: 1.0

  - name: gripper_group_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint5
      - joint6