controller_list:
  - name: hand_ee
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint5
      - joint6
  - name: arm_robot
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    goal_tolerance: 
      joint1: 0.001
      joint2: 0.001
      joint3: 0.001 
      joint4: 0.001

initial:  # Define initial robot poses per group
  - group: hand_ee
    pose: hand_zero
  - group: arm_robot
    pose: arm_home
